version: '3.7'

services:

  nginx:
    image: nginx:1.17-alpine
    container_name: qadamjo-nginx
    restart: unless-stopped
    working_dir: /app
    ports:
      - 20080:80 # frontend
      - 20081:81 # backend
      - 20082:82 # storage
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - db

  php-fpm:
    build: docker/php-fpm
    restart: unless-stopped
    container_name: qadamjo-php
    working_dir: /app
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db

  db:
    #    image: postgres:12.2-alpine
    image: mysql:5.7
    restart: unless-stopped
    ports:
      #      - 5432:5432
      - 33061:3306
    volumes:
      #      - ./docker/storage/psql:/var/lib/postgresql/data:cached
      - ./docker/storage/mysql:/var/lib/mysql
      - ./docker/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: qadamjo
      MYSQL_USER: ROOT_USER
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      #      POSTGRES_USER: qadamjo
      #      POSTGRES_PASSWORD: qadamjo
      #      POSTGRES_DB: qadamjo


